version: "3.7"

services:
  tomcat:
    container_name: ast-cloud-config
    #image: astvision/spring-cloud-config
    image: ast-spring-cloud-config
    hostname: ast-cloud-config
    restart: always
    environment:
      JAVA_OPTS: -Xms128m -Xmx256m -Dspring.profiles.active=production
      CLOUD_CONFIG_PATH: /home/spring/config
      CLOUD_CONFIG_AUTH_ENABLED: "true"
      CLOUD_CONFIG_USERNAME: test
      CLOUD_CONFIG_PASSWORD: test123
    ports:
      - 8888:8888
    volumes:
      - /opt/ast-starter/config:/home/spring/config
    networks:
      - ast_starter
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: 10m

networks:
    ast_starter:
      driver: bridge
